export const options = [
    { value: 'tokio', label: 'Tokio' },
    { value: 'nueva_york', label: 'Nueva York' },
    { value: 'londres', label: 'Londres' },
    { value: 'paris', label: 'París' },
    { value: 'singapur', label: 'Singapur' },
    { value: 'hong_kong', label: 'Hong Kong' },
    { value: 'los_angeles', label: 'Los Ángeles' },
    { value: 'shanghai', label: 'Shanghái' },
    { value: 'seul', label: 'Seúl' },
    { value: 'pekin', label: 'Pekín' },
    { value: 'chicago', label: 'Chicago' },
    { value: 'moscu', label: 'Moscú' },
    { value: 'estambul', label: 'Estambul' },
    { value: 'san_francisco', label: 'San Francisco' },
    { value: 'sidney', label: 'Sídney' },
    { value: 'toronto', label: 'Toronto' },
    { value: 'dubai', label: 'Dubái' },
    { value: 'frankfurt', label: 'Fráncfort' },
    { value: 'boston', label: 'Boston' },
    { value: 'zurich', label: 'Zúrich' },
    { value: 'madrid', label: 'Madrid' },
    { value: 'ciudad_de_mexico', label: 'Ciudad de México' },
    { value: 'buenos_aires', label: 'Buenos Aires' },
    { value: 'sao_paulo', label: 'São Paulo' },
    { value: 'rio_de_janeiro', label: 'Río de Janeiro' },
    { value: 'santiago_cl', label: 'Santiago de Chile' },
    { value: 'bogota', label: 'Bogotá' },
    { value: 'lima_pe', label: 'Lima' },
    { value: 'caracas', label: 'Caracas' },
    { value: 'montreal', label: 'Montreal' },
    { value: 'milan', label: 'Milán' },
    { value: 'roma', label: 'Roma' },
    { value: 'berlin', label: 'Berlín' },
    { value: 'munich', label: 'Múnich' },
    { value: 'hamburgo', label: 'Hamburgo' },
    { value: 'amsterdam', label: 'Ámsterdam' },
    { value: 'bruselas', label: 'Bruselas' },
    { value: 'viena', label: 'Viena' },
    { value: 'estocolmo', label: 'Estocolmo' },
    { value: 'oslo', label: 'Oslo' },
    { value: 'copenhague', label: 'Copenhague' },
    { value: 'dublin', label: 'Dublín' },
    { value: 'lisboa', label: 'Lisboa' },
    { value: 'atenas', label: 'Atenas' },
    { value: 'tel_aviv', label: 'Tel Aviv' },
    { value: 'el_cairo', label: 'El Cairo' },
    { value: 'ciudad_del_cabo', label: 'Ciudad del Cabo' },
    { value: 'johannesburgo', label: 'Johannesburgo' },
    { value: 'nairobi', label: 'Nairobi' },
    { value: 'lagos', label: 'Lagos' },
    { value: 'nueva_delhi', label: 'Nueva Delhi' },
    { value: 'mumbai', label: 'Bombay (Mumbai)' },
    { value: 'bangalore', label: 'Bangalore' },
    { value: 'chennai', label: 'Chennai' },
    { value: 'yakarta', label: 'Yakarta' },
    { value: 'kuala_lumpur', label: 'Kuala Lumpur' },
    { value: 'bangkok', label: 'Bangkok' },
    { value: 'manila', label: 'Manila' },
    { value: 'ho_chi_minh_city', label: 'Ciudad Ho Chi Minh' },
    { value: 'hanoi', label: 'Hanói' },
    { value: 'melbourne', label: 'Melbourne' },
    { value: 'auckland', label: 'Auckland' },
    { value: 'osaka_jp', label: 'Osaka' },
    { value: 'busan', label: 'Busan' },
    { value: 'shenzhen', label: 'Shenzhen' },
    { value: 'guangzhou', label: 'Cantón (Guangzhou)' },
    { value: 'tianjin', label: 'Tianjin' },
    { value: 'taipei', label: 'Taipéi' },
    { value: 'riyadh', label: 'Riad' },
    { value: 'doha', label: 'Doha' },
    { value: 'ankara', label: 'Ankara' },
    { value: 'budapest', label: 'Budapest' },
    { value: 'praga', label: 'Praga' },
    { value: 'varsovia', label: 'Varsovia' },
    { value: 'kiev_ua', label: 'Kiev' },
    { value: 'san_petersburgo', label: 'San Petersburgo' },
    { value: 'sofia', label: 'Sofía' },
    { value: 'zagreb', label: 'Zagreb' },
    { value: 'belgrado', label: 'Belgrado' },
    { value: 'bucharest', label: 'Bucarest' },
    { value: 'riga', label: 'Riga' },
    { value: 'vilnius', label: 'Vilna' },
    { value: 'tallinn', label: 'Tallin' },
    { value: 'helsinki', label: 'Helsinki' },
    { value: 'reykjavik', label: 'Reikiavik' },
    { value: 'quito', label: 'Quito' },
    { value: 'la_paz_bo', label: 'La Paz' },
    { value: 'montevideo', label: 'Montevideo' },
    { value: 'asuncion', label: 'Asunción' },
    { value: 'panama_city', label: 'Ciudad de Panamá' },
    { value: 'san_jose_cr', label: 'San José (Costa Rica)' },
    { value: 'san_salvador', label: 'San Salvador' },
    { value: 'tegucigalpa', label: 'Tegucigalpa' },
    { value: 'guatemala_city', label: 'Ciudad de Guatemala' },
    { value: 'la_habana', label: 'La Habana' },
    { value: 'kingston_jm', label: 'Kingston' },
    { value: 'puerto_principe', label: 'Puerto Príncipe' },
    { value: 'san_juan_pr', label: 'San Juan (Puerto Rico)' },
    { value: 'philadelphia', label: 'Filadelfia' },
    { value: 'dallas', label: 'Dallas' },
    { value: 'houston', label: 'Houston' },
    { value: 'miami', label: 'Miami' },
    { value: 'atlanta', label: 'Atlanta' },
    { value: 'seattle', label: 'Seattle' },
    { value: 'denver', label: 'Denver' },
    { value: 'phoenix', label: 'Phoenix' },
    { value: 'san_diego', label: 'San Diego' },
    { value: 'detroit', label: 'Detroit' },
    { value: 'vancouver', label: 'Vancouver' },
    { value: 'calgary', label: 'Calgary' },
    { value: 'edmonton', label: 'Edmonton' },
    { value: 'wellington', label: 'Wellington' },
    { value: 'christchurch', label: 'Christchurch' },
    { value: 'brisbane', label: 'Brisbane' },
    { value: 'perth', label: 'Perth' },
    { value: 'adelaide', label: 'Adelaida' },
    { value: 'nagoya', label: 'Nagoya' },
    { value: 'fukuoka', label: 'Fukuoka' },
    { value: 'sapporo', label: 'Sapporo' },
    { value: 'dusseldorf', label: 'Dusseldorf' },
    { value: 'stuttgart', label: 'Stuttgart' },
    { value: 'koln', label: 'Colonia' },
    { value: 'lyon', label: 'Lyon' },
    { value: 'marsella', label: 'Marsella' },
    { value: 'burdeos', label: 'Burdeos' },
    { value: 'manchester', label: 'Mánchester' },
    { value: 'birmingham', label: 'Birmingham' },
    { value: 'glasgow', label: 'Glasgow' },
    { value: 'edinburgh', label: 'Edimburgo' },
    { value: 'napoles', label: 'Nápoles' },
    { value: 'turin', label: 'Turín' },
    { value: 'florencia', label: 'Florencia' },
    { value: 'barcelona', label: 'Barcelona' },
    { value: 'valencia_es', label: 'Valencia' },
    { value: 'sevilla', label: 'Sevilla' },
    { value: 'cork', label: 'Cork' },
    { value: 'ginebra', label: 'Ginebra' },
    { value: 'basilea', label: 'Basilea' },
    { value: 'gotemburgo', label: 'Gotemburgo' },
    { value: 'malmo', label: 'Malmö' },
    { value: 'amberes', label: 'Amberes' },
    { value: 'gante', label: 'Gante' },
    { value: 'rotterdam', label: 'Róterdam' },
    { value: 'utrecht', label: 'Utrecht' },
    { value: 'oporto', label: 'Oporto' },
    { value: 'casablanca', label: 'Casablanca' },
    { value: 'argel', label: 'Argel' },
    { value: 'tunis', label: 'Túnez' },
    { value: 'tripoli_ly', label: 'Trípoli' },
    { value: 'khartoum', label: 'Jartum' },
    { value: 'addis_abeba', label: 'Adís Abeba' },
    { value: 'dar_es_salaam', label: 'Dar es-Salam' },
    { value: 'kinshasa', label: 'Kinshasa' },
    { value: 'abidjan', label: 'Abiyán' },
    { value: 'accra', label: 'Acra' },
    { value: 'harare', label: 'Harare' },
    { value: 'lusaka', label: 'Lusaka' },
    { value: 'luanda', label: 'Luanda' },
    { value: 'dakar', label: 'Dakar' },
    { value: 'rabat', label: 'Rabat' },
    { value: 'amman', label: 'Amán' },
    { value: 'beirut', label: 'Beirut' },
    { value: 'bagdad', label: 'Bagdad' },
    { value: 'teheran', label: 'Teherán' },
    { value: 'karachi', label: 'Karachi' },
    { value: 'lahore', label: 'Lahore' },
    { value: 'daca', label: 'Daca' },
    { value: 'rangun', label: 'Rangún' },
    { value: 'colombo', label: 'Colombo' },
    { value: 'katmandu', label: 'Katmandú' },
    { value: 'pyongyang', label: 'Pionyang' },
    { value: 'ulaanbaatar', label: 'Ulán Bator' },
    { value: 'phnom_penh', label: 'Nom Pen' },
    { value: 'vientiane', label: 'Vientián' },
    { value: 'bandar_seri_begawan', label: 'Bandar Seri Begawan' },
    { value: 'surabaya', label: 'Surabaya' },
    { value: 'macau', label: 'Macao' },
    { value: 'cebu', label: 'Cebú' },
    { value: 'darwin', label: 'Darwin' },
    { value: 'hobart', label: 'Hobart' },
    { value: 'canberra', label: 'Canberra' },
    { value: 'suva', label: 'Suva' },
    { value: 'porto_alegre', label: 'Porto Alegre' },
    { value: 'salvador_br', label: 'Salvador (Bahía)' },
    { value: 'recife', label: 'Recife' },
    { value: 'medellin', label: 'Medellín' },
    { value: 'cali_co', label: 'Cali' },
    { value: 'barranquilla', label: 'Barranquilla' },
    { value: 'guayaquil', label: 'Guayaquil' },
    { value: 'cordoba_ar', label: 'Córdoba (Argentina)' },
    { value: 'rosario', label: 'Rosario' },
    { value: 'santo_domingo', label: 'Santo Domingo' },
    { value: 'tijuana', label: 'Tijuana' },
    { value: 'guadalajara_mx', label: 'Guadalajara' },
    { value: 'monterrey', label: 'Monterrey' },
    { value: 'chihuahua', label: 'Chihuahua' },
    { value: 'el_paso', label: 'El Paso' },
    { value: 'albuquerque', label: 'Albuquerque' },
    { value: 'salt_lake_city', label: 'Salt Lake City' },
    { value: 'las_vegas', label: 'Las Vegas' },
    { value: 'portland_us', label: 'Portland (EE. UU.)' },
    { value: 'san_antonio', label: 'San Antonio' },
    { value: 'orlando', label: 'Orlando' },
    { value: 'tampa', label: 'Tampa' },
    { value: 'cleveland', label: 'Cleveland' },
    { value: 'pittsburgh', label: 'Pittsburgh' },
    { value: 'cincinnati', label: 'Cincinnati' },
    { value: 'milwaukee', label: 'Milwaukee' },
    { value: 'minneapolis', label: 'Mineápolis' },
    { value: 'kansas_city', label: 'Kansas City' },
    { value: 'quebec_city', label: 'Ciudad de Quebec' },
    { value: 'ottawa', label: 'Ottawa' },
    { value: 'halifax_ca', label: 'Halifax' },
    { value: 'aachen', label: 'Aquisgrán' },
    { value: 'aberdeen', label: 'Aberdeen' },
    { value: 'abuja', label: 'Abuya' },
    { value: 'adana', label: 'Adana' },
    { value: 'agadir', label: 'Agadir' },
    { value: 'agra', label: 'Agra' },
    { value: 'almaty', label: 'Almaty' },
    { value: 'amritsar', label: 'Amritsar' },
    { value: 'belfast', label: 'Belfast' },
    { value: 'bilbao', label: 'Bilbao' },
    { value: 'bologna', label: 'Bolonia' },
    { value: 'bratislava', label: 'Bratislava' },
    { value: 'bremen', label: 'Bremen' },
    { value: 'bursa', label: 'Bursa' },
    { value: 'campo_grande', label: 'Campo Grande' },
    { value: 'cartagena_co', label: 'Cartagena (Colombia)' },
    { value: 'catania', label: 'Catania' },
    { value: 'ciudad_del_este', label: 'Ciudad del Este' },
    { value: 'cordoba_es', label: 'Córdoba (España)' },
    { value: 'curitiba', label: 'Curitiba' },
    { value: 'denpasar', label: 'Denpasar' },
    { value: 'dresden', label: 'Dresde' },
    { value: 'dubrovnik', label: 'Dubrovnik' },
    { value: 'gaziantep', label: 'Gaziantep' },
    { value: 'genova', label: 'Génova' },
    { value: 'gyeongju', label: 'Gyeongju' },
    { value: 'hangzhou', label: 'Hangzhou' },
    { value: 'hiroshima', label: 'Hiroshima' },
    { value: 'innsbruck', label: 'Innsbruck' },
    { value: 'izmir', label: 'Izmir' },
    { value: 'jaipur', label: 'Jaipur' },
    { value: 'kabul', label: 'Kabul' },
    { value: 'kaohsiung', label: 'Kaohsiung' },
    { value: 'krakow', label: 'Cracovia' },
    { value: 'kyoto', label: 'Kioto' },
    { value: 'leipzig', label: 'Leipzig' },
    { value: 'liverpool', label: 'Liverpool' },
    { value: 'lublin', label: 'Lublin' },
    { value: 'malaga', label: 'Málaga' },
    { value: 'marrakech', label: 'Marrakech' },
    { value: 'mesina', label: 'Mesina' },
    { value: 'nanjing', label: 'Nankín' },
    { value: 'nice', label: 'Niza' },
    { value: 'nuremberg', label: 'Núremberg' },
    { value: 'okinawa', label: 'Okinawa' },
    { value: 'palermo', label: 'Palermo' },
    { value: 'poznan', label: 'Poznan' },
    { value: 'san_sebastian', label: 'San Sebastián' },
    { value: 'sapporo_jp', label: 'Sapporo' },
    { value: 'shenyang', label: 'Shenyang' },
    { value: 'taichung', label: 'Taichung' },
    { value: 'tbilisi', label: 'Tiflis' },
    { value: 'thessaloniki', label: 'Salónica' },
    { value: 'verona', label: 'Verona' },
    { value: 'warsaw', label: 'Varsovia' },
    { value: 'wroclaw', label: 'Breslavia' },
    { value: 'xian', label: 'Xi\'an' },
    { value: 'yokohama', label: 'Yokohama' },
    { value: 'zaragoza', label: 'Zaragoza' },
    { value: 'acapulco', label: 'Acapulco' },
    { value: 'algiers', label: 'Argel' },
    { value: 'antananarivo', label: 'Antananarivo' },
    { value: 'apia', label: 'Apia' },
    { value: 'astana', label: 'Astaná' },
    { value: 'bandung', label: 'Bandung' },
    { value: 'belem', label: 'Belém' },
    { value: 'brazzaville', label: 'Brazzaville' },
    { value: 'cologne', label: 'Colonia' },
    { value: 'curacao', label: 'Curazao' },
    { value: 'dhaka', label: 'Daca' },
    { value: 'durban', label: 'Durban' },
    { value: 'gaza', label: 'Gaza' },
    { value: 'georgetown', label: 'Georgetown (Guyana)' },
    { value: 'gijon', label: 'Gijón' },
    { value: 'hamburg', label: 'Hamburgo' },
    { value: 'harbin', label: 'Harbin' },
    { value: 'honolulu', label: 'Honolulu' },
    { value: 'kobe', label: 'Kōbe' },
    { value: 'kutaisi', label: 'Kutaisi' },
    { value: 'libreville', label: 'Libreville' },
    { value: 'manaus', label: 'Manaus' },
    { value: 'mazatlan', label: 'Mazatlán' },
    { value: 'minsk', label: 'Minsk' },
    { value: 'monrovia', label: 'Monrovia' },
    { value: 'nagasaki', label: 'Nagasaki' },
    { value: 'nassau', label: 'Nasáu' },
    { value: 'porto_novo', label: 'Porto Novo' },
    { value: 'pune', label: 'Pune' },
    { value: 'san_pedro_sula', label: 'San Pedro Sula' },
    { value: 'sarajevo', label: 'Sarajevo' },
    { value: 'tampico', label: 'Tampico' },
    { value: 'tashkent', label: 'Taskent' },
    { value: 'tirana', label: 'Tirana' },
    { value: 'toulouse', label: 'Toulouse' },
    { value: 'turku', label: 'Turku' },
    { value: 'vaduz', label: 'Vaduz' },
    { value: 'valletta', label: 'La Valeta' },
    { value: 'wuhan', label: 'Wuhan' },
    { value: 'yaounde', label: 'Yaundé' },
    { value: 'yerevan', label: 'Ereván' },
    { value: 'zanzibar', label: 'Zanzíbar' },
    { value: 'zhengzhou', label: 'Zhengzhou' },
    { value: 'ad_dahira', label: 'Ad Dakhiliyah (Omán)' },
    { value: 'ajaccio', label: 'Ajaccio' },
    { value: 'akureyri', label: 'Akureyri' },
    { value: 'al_khobar', label: 'Al Khobar' },
    { value: 'aleppo', label: 'Alepo' },
    { value: 'anadyr', label: 'Anádyr' },
    { value: 'anqing', label: 'Anqing' },
    { value: 'antakya', label: 'Antioquía (Antakya)' },
    { value: 'aqaba', label: 'Áqaba' },
    { value: 'arbil', label: 'Erbil' },
    { value: 'as_suwayda', label: 'As-Suwayda' },
    { value: 'astrakhan', label: 'Astracán' },
    { value: 'augsburg', label: 'Augsburgo' },
    { value: 'badajoz', label: 'Badajoz' },
    { value: 'baku', label: 'Bakú' },
    { value: 'bali_denpasar', label: 'Denpasar (Bali)' },
    { value: 'bamako', label: 'Bamako' },
    { value: 'bandar_abbas', label: 'Bandar Abbás' },
    { value: 'bangui', label: 'Bangui' },
    { value: 'basra', label: 'Basora' },
    { value: 'batumi', label: 'Batumi' },
    { value: 'beira', label: 'Beira' },
    { value: 'benguela', label: 'Benguela' },
    { value: 'timbu', label: 'Timbu (Bután)' },
    { value: 'bishkek', label: 'Biskek' },
    { value: 'blantyre', label: 'Blantyre' },
    { value: 'braunswick', label: 'Brunswick' },
    { value: 'bray', label: 'Bray' },
    { value: 'bridgetown', label: 'Bridgetown' },
    { value: 'bristol', label: 'Bristol' },
    { value: 'caceres', label: 'Cáceres' },
    { value: 'cambridge', label: 'Cambridge' },
    { value: 'carthage', label: 'Cartago' },
    { value: 'charlotte', label: 'Charlotte' },
    { value: 'charlottetown', label: 'Charlottetown' },
    { value: 'chengdu', label: 'Chengdú' },
    { value: 'chongqing', label: 'Chongqing' },
    { value: 'cluj_napoca', label: 'Cluj-Napoca' },
    { value: 'duisburg', label: 'Duisburgo' },
    { value: 'erzurum', label: 'Erzurum' },
    { value: 'essen', label: 'Essen' },
    { value: 'figueres', label: 'Figueras' },
    { value: 'freetown', label: 'Freetown' },
    { value: 'librevillegb', label: 'Libreville (Gabón)' },
    { value: 'guam', label: 'Agaña (Guam)' },
    { value: 'hamilton_bm', label: 'Hamilton (Bermudas)' },
    { value: 'hyderabad_in', label: 'Hyderabad (India)' },
    { value: 'ibiza', label: 'Ibiza' },
    { value: 'incheon', label: 'Incheon' },
    { value: 'jabalpur', label: 'Jabalpur' },
    { value: 'jacksonville', label: 'Jacksonville' },
    { value: 'kaduna', label: 'Kaduna' },
    { value: 'katowice', label: 'Katowice' },
    { value: 'kumasi', label: 'Kumasi' },
    { value: 'kuwait_city', label: 'Ciudad de Kuwait' },
    { value: 'lancaster', label: 'Lancaster' },
    { value: 'las_palmas', label: 'Las Palmas de Gran Canaria' },
    { value: 'leeds', label: 'Leeds' },
    { value: 'linz', label: 'Linz' },
    { value: 'lome', label: 'Lomé' },
    { value: 'luxembourg_city', label: 'Ciudad de Luxemburgo' },
    { value: 'madras', label: 'Madrás (Chennai)' },
    { value: 'magdeburg', label: 'Magdeburgo' },
    { value: 'maracaibo', label: 'Maracaibo' },
    { value: 'masqat', label: 'Mascate' },
    { value: 'medan', label: 'Medan' },
    { value: 'monaco', label: 'Mónaco' },
    { value: 'noumea', label: 'Numea' },
    { value: 'novosibirsk', label: 'Novosibirsk' },
    { value: 'odessa', label: 'Odesa' },
    { value: 'oxford', label: 'Oxford' },
    { value: 'palma_mallorca', label: 'Palma de Mallorca' },
    { value: 'paphos', label: 'Pafos' },
    { value: 'port_au_prince', label: 'Puerto Príncipe' },
    { value: 'port_louis', label: 'Port Louis' },
    { value: 'port_more', label: 'Portmore' },
    { value: 'port_of_spain', label: 'Puerto España' },
    { value: 'port_vila', label: 'Port Vila' },
    { value: 'santa_cruz_tenerife', label: 'Santa Cruz de Tenerife' },
    { value: 'st_johns_ca', label: 'St. John\'s (Canadá)' },
    { value: 'st_louis', label: 'San Luis (Misuri)' },
    { value: 'sucre', label: 'Sucre (Bolivia)' },
    { value: 'victoria_ca', label: 'Victoria (Canadá)' },
    { value: 'vladivostok', label: 'Vladivostok' },
    { value: 'washington_dc', label: 'Washington D. C.' },
    { value: 'chiang_mai', label: 'Chiang Mai' },
    { value: 'geneva', label: 'Ginebra' },
    { value: 'ghent', label: 'Gante' },
    { value: 'hamilton_nz', label: 'Hamilton (Nueva Zelanda)' },
    { value: 'other', label: 'Otra Ciudad (Especifique)' },
    { value: 'aarhus', label: 'Aarhus' },
    { value: 'abu_dhabi', label: 'Abu Dabi' },
    { value: 'acra_ghana', label: 'Accra' },
    { value: 'addis_ababa_et', label: 'Adís Abeba' },
    { value: 'adelaide_au', label: 'Adelaida' },
    { value: 'al_ain', label: 'Al Ain' },
    { value: 'albuquerque_us', label: 'Albuquerque' },
    { value: 'alexandria_eg', label: 'Alejandría' },
    { value: 'alicante_es', label: 'Alicante' },
    { value: 'amman_jo', label: 'Amán' },
    { value: 'ancona_it', label: 'Ancona' },
    { value: 'antwerp_be', label: 'Amberes' },
    { value: 'arica_cl', label: 'Arica' },
    { value: 'ashgabat_tm', label: 'Asjabad' },
    { value: 'asmera_er', label: 'Asmara' },
    { value: 'astrakhan_ru', label: 'Astracán' },
    { value: 'auckland_nz', label: 'Auckland' },
    { value: 'baghdad_iq', label: 'Bagdad' },
    { value: 'baltimore_us', label: 'Baltimore' },
    { value: 'barnaul_ru', label: 'Barnaul' },
    { value: 'bath_uk', label: 'Bath' },
    { value: 'bayonne_fr', label: 'Bayona' },
    { value: 'beijing_cn', label: 'Pekín' },
    { value: 'bellingham_us', label: 'Bellingham' },
    { value: 'benares_in', label: 'Benarés (Varanasi)' },
    { value: 'bergen_no', label: 'Bergen' },
    { value: 'bikaner_in', label: 'Bikaner' },
    { value: 'bilbao_es', label: 'Bilbao' },
    { value: 'bologna_it', label: 'Bolonia' },
    { value: 'bordeaux_fr', label: 'Burdeos' },
    { value: 'braga_pt', label: 'Braga' },
    { value: 'bristol_uk', label: 'Bristol' },
    { value: 'bursa_tr', label: 'Bursa' },
    { value: 'cairns_au', label: 'Cairns' },
    { value: 'cambridge_uk', label: 'Cambridge' },
    { value: 'cape_town_za', label: 'Ciudad del Cabo' },
    { value: 'charleston_us', label: 'Charleston' },
    { value: 'chengdu_cn', label: 'Chengdú' },
    { value: 'chisinau_md', label: 'Chisináu' },
    { value: 'colombo_lk', label: 'Colombo' },
    { value: 'como_it', label: 'Como' },
    { value: 'coimbra_pt', label: 'Coímbra' },
    { value: 'cologne_de', label: 'Colonia' },
    { value: 'daegu_kr', label: 'Daegu' },
    { value: 'dakar_sn', label: 'Dakar' },
    { value: 'damascus_sy', label: 'Damasco' },
    { value: 'darmstadt_de', label: 'Darmstadt' },
    { value: 'delhi_in', label: 'Delhi' },
    { value: 'dortmund_de', label: 'Dortmund' },
    { value: 'dresden_de', label: 'Dresde' },
    { value: 'edmonton_ca', label: 'Edmonton' },
    { value: 'eindhoven_nl', label: 'Eindhoven' },
    { value: 'erbil_iq', label: 'Erbil' },
    { value: 'eskisehir_tr', label: 'Eskişehir' },
    { value: 'florence_it', label: 'Florencia' },
    { value: 'fortaleza_br', label: 'Fortaleza' },
    { value: 'fukuoka_jp', label: 'Fukuoka' },
    { value: 'galway_ie', label: 'Galway' },
    { value: 'gaziantep_tr', label: 'Gaziantep' },
    { value: 'graz_at', label: 'Graz' },
    { value: 'guadalajara_es', label: 'Guadalajara (España)' },
    { value: 'gwangju_kr', label: 'Gwangju' },
    { value: 'haifa_il', label: 'Haifa' },
    { value: 'hangzhou_cn', label: 'Hangzhou' },
    { value: 'hannover_de', label: 'Hanóver' },
    { value: 'harare_zw', label: 'Harare' },
    { value: 'helsinki_fi', label: 'Helsinki' },
    { value: 'ho_chi_minh_vn', label: 'Ciudad Ho Chi Minh' },
    { value: 'innsbruck_at', label: 'Innsbruck' },
    { value: 'islamabad_pk', label: 'Islamabad' },
    { value: 'jaipur_in', label: 'Jaipur' },
    { value: 'johannesburg_za', label: 'Johannesburgo' },
    { value: 'kabul_af', label: 'Kabul' },
    { value: 'kaduna_ng', label: 'Kaduna' },
    { value: 'kansas_city_us', label: 'Kansas City' },
    { value: 'karachi_pk', label: 'Karachi' },
    { value: 'kingston_ca', label: 'Kingston (Canadá)' },
    { value: 'krakow_pl', label: 'Cracovia' },
    { value: 'kyoto_jp', label: 'Kioto' },
    { value: 'leeds_uk', label: 'Leeds' },
    { value: 'lima_pe2', label: 'Lima (Perú)' },
    { value: 'linz_at', label: 'Linz' },
    { value: 'lisbon_pt', label: 'Lisboa' },
    { value: 'liverpool_uk', label: 'Liverpool' },
    { value: 'lublin_pl', label: 'Lublin' },
    { value: 'luqa_mt', label: 'Luqa (Malta)' },
    { value: 'luxembourg_lu', label: 'Ciudad de Luxemburgo' },
    { value: 'lyon_fr', label: 'Lyon' },
    { value: 'macao_mo', label: 'Macao' },
    { value: 'madrid_es', label: 'Madrid' },
    { value: 'malaga_es', label: 'Málaga' },
    { value: 'manaus_br', label: 'Manaus' },
    { value: 'maracaibo_ve', label: 'Maracaibo' },
    { value: 'marrakech_ma', label: 'Marrakech' },
    { value: 'medan_id', label: 'Medan' },
    { value: 'minsk_by', label: 'Minsk' },
    { value: 'monrovia_lr', label: 'Monrovia' },
    { value: 'nairobi_ke', label: 'Nairobi' },
    { value: 'nanjing_cn', label: 'Nankín' },
    { value: 'naples_it', label: 'Nápoles' },
    { value: 'nice_fr', label: 'Niza' },
    { value: 'novosibirsk_ru', label: 'Novosibirsk' },
    { value: 'nuremberg_de', label: 'Núremberg' },
    { value: 'odessa_ua', label: 'Odesa' },
    { value: 'osaka_jp2', label: 'Osaka' },
    { value: 'oslo_no', label: 'Oslo' },
    { value: 'palermo_it', label: 'Palermo' },
    { value: 'paphos_cy', label: 'Pafos' },
    { value: 'paris_fr', label: 'París' },
    { value: 'porto_pt', label: 'Oporto' },
    { value: 'poznan_pl', label: 'Poznan' },
    { value: 'prague_cz', label: 'Praga' },
    { value: 'pune_in', label: 'Pune' },
    { value: 'quebec_ca', label: 'Ciudad de Quebec' },
    { value: 'quito_ec', label: 'Quito' },
    { value: 'rabat_ma', label: 'Rabat' },
    { value: 'rangoon_mm', label: 'Rangún' },
    { value: 'recife_br', label: 'Recife' },
    { value: 'reykjavik_is', label: 'Reikiavik' },
    { value: 'riga_lv', label: 'Riga' },
    { value: 'rome_it', label: 'Roma' },
    { value: 'rotterdam_nl', label: 'Róterdam' },
    { value: 'san_juan_us', label: 'San Juan (EE. UU.)' },
    { value: 'sarajevo_ba', label: 'Sarajevo' },
    { value: 'seattle_us', label: 'Seattle' },
    { value: 'seoul_kr', label: 'Seúl' },
    { value: 'shenyang_cn', label: 'Shenyang' },
    { value: 'singapore_sg', label: 'Singapur' },
    { value: 'sofia_bg', label: 'Sofía' },
    { value: 'st_petersburg_ru', label: 'San Petersburgo' },
    { value: 'stockholm_se', label: 'Estocolmo' },
    { value: 'sucre_bo', label: 'Sucre (Bolivia)' },
    { value: 'taichung_tw', label: 'Taichung' },
    { value: 'tallinn_ee', label: 'Tallin' },
    { value: 'tampa_us', label: 'Tampa' },
    { value: 'tashkent_uz', label: 'Taskent' },
    { value: 'tbilisi_ge', label: 'Tiflis' },
    { value: 'tel_aviv_il', label: 'Tel Aviv' },
    { value: 'tijuana_mx', label: 'Tijuana' },
    { value: 'tokyo_jp', label: 'Tokio' },
    { value: 'toulouse_fr', label: 'Toulouse' },
    { value: 'tripoli_lb', label: 'Trípoli (Líbano)' },
    { value: 'tunis_tn', label: 'Túnez' },
    { value: 'turin_it', label: 'Turín' },
    { value: 'turku_fi', label: 'Turku' },
    { value: 'ulaanbaatar_mn', label: 'Ulán Bator' },
    { value: 'valencia_es2', label: 'Valencia' },
    { value: 'vancouver_ca', label: 'Vancouver' },
    { value: 'vienna_at', label: 'Viena' },
    { value: 'vientiane_la', label: 'Vientián' },
    { value: 'vilnius_lt', label: 'Vilna' },
    { value: 'vladivostok_ru', label: 'Vladivostok' },
    { value: 'wellington_nz', label: 'Wellington' },
    { value: 'xian_cn', label: 'Xi\'an' },
    { value: 'yaounde_cm', label: 'Yaundé' },
    { value: 'yerevan_am', label: 'Ereván' },
    { value: 'yokohama_jp2', label: 'Yokohama' },
    { value: 'zaragoza_es', label: 'Zaragoza' },
    { value: 'zhengzhou_cn', label: 'Zhengzhou' },
    { value: 'zurich_ch', label: 'Zúrich' },
    { value: 'zanzibar_tz', label: 'Zanzíbar' },
    { value: 'valparaiso_cl', label: 'Valparaíso' },
    { value: 'cartagena_es', label: 'Cartagena (España)' },
    { value: 'monaco_mc', label: 'Mónaco' },
    { value: 'san_jose_us', label: 'San José (EE. UU.)' },
    { value: 'guam_us', label: 'Guam' },
    { value: 'nicosia_cy', label: 'Nicosia' },
    { value: 'malabo_gq', label: 'Malabo' },
    { value: 'libreville_ga', label: 'Libreville' }
];